### PR TITLE
Get `buf` binary using the tag directly

### LINKED ISSUE #18: Cannot get versions past the first page of Release API results
Hey, folks! Ran into a weird bug today with this action. On a PR, v0.41.0 of buf was configured to be run against but we received the following error:

```
Run bufbuild/buf-setup-action@v0.1.0
Setting up buf version "0.41.0"
Resolving the download URL for the current platform...
Error: Unable to find Buf version "0.41.0" for platform "Linux" and architecture "x86_64".
```

The release does exist, and has a Linux/x86_64 version available to download, and there are currently no incidents on the GH APIs. Looking into the action's definition further, the [List Releases](https://docs.github.com/en/rest/reference/repos#list-releases) endpoint is called, but [without pagination](https://github.com/bufbuild/buf-setup-action/blob/3424b70/src/buf.ts#L115-L121). This causes the API to default to 30 results per page, and as of the release of v1.0.0-rc8 two hours ago, v0.41.0 became the 31st release. 

We encountered this on v0.1.0 of the Action, but this affects all versions through latest.

### PR DESCRIPTION
**Pull request by doriable**
This uses the [get a release by tag name endpoint](https://docs.github.com/en/rest/reference/repos#get-a-release-by-tag-name) to get specific releases, but defaults to the [list releases](https://docs.github.com/en/rest/reference/repos#get-a-release-by-tag-name) endpoint for the `latest` configuration. Note, we are not able to use the [get latest release](https://docs.github.com/en/rest/reference/repos#get-a-release-by-tag-name) endpoint because this only applies to non-prerelease (and non-draft) versions.

Fixes #18

### CODE REVIEW

File: src/buf.ts [hunk 1]
```diff
@@ -112,46 +112,46 @@ async function getDownloadURL(version: string, githubToken: string): Promise<str
...
+        owner: 'bufbuild',
+        repo: 'buf',
+        per_page: 1,
+      }
+    );
+    for (const asset of releases[0].assets) {
+      if (assetName === asset.name) {
+        return asset.browser_download_url;
+      }
+    }
```
Comment (amckinney) [inline src/buf.ts:128]: This refactor means that if an asset was not found with the `/releases` endpoint above, we will still try the `/releases/tags` endpoint.

Previously, if an asset was not resolved from `latest`, we would `break` in the `switch`  return the following:

```
  return {
    message: `Unable to find Buf version "${version}" for platform "${platform}" and architecture "${architecture}".`
  };
```

With that said, if they configure the `latest` keyword in the action, then we'll always prioritize the latest release (via the `/releases` endpoint) and never resolve their specific tag named `latest`. It might be best to just return early here and prevent a second RPC that is destined to fail.

```suggestion
    }
    return {
      message: `Unable to find Buf version "${version}" for platform "${platform}" and architecture "${architecture}".`
    };
```

**Review by amckinney — APPROVED** [review]
I think we should return early when an asset isn't found from the `latest` keyword, but otherwise looks good!

File: src/buf.ts (hunk 1 above)
Comment (doriable) [reply src/buf.ts:128]: That's a good call, big fan of the early return! :D
